
version: "2.2"
services:
  web:
    build: nginx-php
    ports:
      - "8080:80"
    networks:
      - main
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - main

networks:
  main:
